### ISSUE TITLE
Dataset issue

### ISSUE THREAD

**Issue by vedantpatil26** [emotion-analysis-project/SemEval2025-Task11#2]
Where can i get the dataset

**Comment by shmuhammadd** [comment]
Hi @vedantpatil26 

Visit the official competition page on Codabench, register and follow the steps below to download the dataset: https://www.codabench.org/competitions/3863/


<img width="444" alt="image" src="https://github.com/user-attachments/assets/0c928820-ff00-4e65-b3df-e2befe3b3c53">

**Comment by SJabin** [comment]
Hi @shmuhammadd, 

The "Files" tab is not available on my end. 
Can you please check?

Thanks.

![image](https://github.com/user-attachments/assets/c226f3bf-1d65-4106-8f7f-42233e4c638d)

**Comment by nedjmaou** [comment]
Hi @SJabin did you create an account on CodaBench and register on the competition webpage?

**Comment by SJabin** [comment]
Yes, I did.

**Comment by nedjmaou** [comment]
@SJabin can you check now? Let us know if it's still not working.
