### ISSUE TITLE
Dataset Issue

### ISSUE THREAD

**Issue by aishik-rakshit** [emotion-analysis-project/SemEval2025-Task11#3]
![image](https://github.com/user-attachments/assets/49796a09-73a7-44c8-9bc8-cdea274353c9)

I am not able to see a files tab here

**Comment by nedjmaou** [comment]
@aishik-rakshit  did you create an account on CodaBench, register on the competition webpage and got your request approved?

**Comment by aamanp** [comment]
Hi! I am not able to see the files tab. I have already created an account on CodaBench and get approved


![Captura de pantalla 2024-09-19 161844](https://github.com/user-attachments/assets/1499f1e0-641a-4e39-b26d-6e1a22f10b90)

**Comment by nedjmaou** [comment]
Hi @aamanp can you try again now?

**Comment by aamanp** [comment]
Yes, now it's available, thank you for solving it!
